""" Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        
    By considering the terms in the Fibonacci sequence whose values
    do not exceed four million, find the sum of the even-valued terms.
"""

def fib (i):
    if i <= 0:
        return 1
    if i == 1:
        return 2
    return fib(i-1) + fib(i-2)

def even_fibonacci (m):
    i=0
    f = fib(i)
    while f <= m:
        if f%2 == 0:
            yield f
        i += 1
        f = fib(i)

print(sum(even_fibonacci(4000000)))
